#config_version=6

# Hitting drop targets on right

mode:
  start_events: start_mode_rightdrops
  stop_events: stop_mode_rightdrops
  priority: 201

shots:
  right_drop_target_1:
    switch: s_right_drop_target_1
  right_drop_target_2:
    switch: s_right_drop_target_2
  right_drop_target_3:
    switch: s_right_drop_target_3
  right_drop_target_4:
    switch: s_right_drop_target_4
  right_drop_target_5:
    switch: s_right_drop_target_5


shot_groups:
  rightdrops:
    shots: 
      right_drop_target_1,
      right_drop_target_2,
      right_drop_target_3,
      right_drop_target_4,
      right_drop_target_5

variable_player:
  rightdrops_hit:
    score: 5_000

sound_player:
    rightdrops_hit: rightdrops_effect
