#config_version=5


#================================================
# HARDWARE
# Switch out for real/virtual machine
#================================================

hardware:
 platform: lisy
lisy:
 connection: network
 network_port: 5963
 poll_hz: 100
 network_host: 192.168.80.1

hardware_sound_systems:
  default:
    label: LISY
  
# hardware:
#   platform: smart_virtual

# virtual_platform_start_active_switches:
#   - s_trough_left
#   - s_trough_right
#   - s_outhole

game:
  balls_per_game: 3

machine:
  balls_installed: 3

modes:
  - base
  - autoResetDrops
  - lockBalls


  
#================================================
# SWITCHES
# Configured as per Gottlieb manual
#================================================

switches:
  
  # zzz_switch_00:
  #   number: 00  
  # zzz_switch_01:
  #   number: 01
  # zzz_switch_02:
  #   number: 02
  # zzz_switch_03:
  #   number: 03
  # zzz_switch_04:
  #   number: 04
  # zzz_switch_05:
  #   number: 05
  # zzz_switch_06:
  #   number: 06
  # zzz_switch_07:
  #   number: 07
  # zzz_switch_08:
  #   number: 08
  # zzz_switch_09:
  #   number: 09

 
  # zzz_switch_10:
  #   number: 10  
  # zzz_switch_11:
  #   number: 11
  # zzz_switch_12:
  #   number: 12
  # zzz_switch_13:
  #   number: 13
  # zzz_switch_14:
  #   number: 14
  # zzz_switch_15:
  #   number: 15
  # zzz_switch_16:
  #   number: 16
  # zzz_switch_17:
  #   number: 17
  # zzz_switch_18:
  #   number: 18
  # zzz_switch_19:
  #   number: 19

 
  # zzz_switch_20:
  #   number: 20  
  # zzz_switch_21:
  #   number: 21
  # zzz_switch_22:
  #   number: 22
  # zzz_switch_23:
  #   number: 23
  # zzz_switch_24:
  #   number: 24
  # zzz_switch_25:
  #   number: 25
  # zzz_switch_26:
  #   number: 26
  # zzz_switch_27:
  #   number: 27
  # zzz_switch_28:
  #   number: 28
  # zzz_switch_29:
  #   number: 29

 
  # zzz_switch_30:
  #   number: 30  
  # zzz_switch_31:
  #   number: 31
  # zzz_switch_32:
  #   number: 32
  # zzz_switch_33:
  #   number: 33
  # zzz_switch_34:
  #   number: 34
  # zzz_switch_35:
  #   number: 35
  # zzz_switch_36:
  #   number: 36
  # zzz_switch_37:
  #   number: 37
  # zzz_switch_38:
  #   number: 38
  # zzz_switch_39:
  #   number: 39

 
  # zzz_switch_40:
  #   number: 40  
  # zzz_switch_41:
  #   number: 41
  # zzz_switch_42:
  #   number: 42
  # zzz_switch_43:
  #   number: 43
  # zzz_switch_44:
  #   number: 44
  # zzz_switch_45:
  #   number: 45
  # zzz_switch_46:
  #   number: 46
  # zzz_switch_47:
  #   number: 47
  # zzz_switch_48:
  #   number: 48
  # zzz_switch_49:
  #   number: 49

  # zzz_switch_50:
  #   number: 50  
  # zzz_switch_51:
  #   number: 51
  # zzz_switch_52:
  #   number: 52
  # zzz_switch_53:
  #   number: 53
  # zzz_switch_54:
  #   number: 54
  # zzz_switch_55:
  #   number: 55
  # zzz_switch_56:
  #   number: 56
  # zzz_switch_57:
  #   number: 57
  # zzz_switch_58:
  #   number: 58
  # zzz_switch_59:
  #   number: 59

 
  # zzz_switch_60:
  #   number: 60  
  # zzz_switch_61:
  #   number: 61
  # zzz_switch_62:
  #   number: 62
  # zzz_switch_63:
  #   number: 63
  # zzz_switch_64:
  #   number: 64
  # zzz_switch_65:
  #   number: 65
  # zzz_switch_66:
  #   number: 66
  # zzz_switch_67:
  #   number: 67
  # zzz_switch_68:
  #   number: 68
  # zzz_switch_69:
  #   number: 69

  # zzz_switch_70:
  #   number: 70  
  # zzz_switch_71:
  #   number: 71
  # zzz_switch_72:
  #   number: 72
  # zzz_switch_73:
  #   number: 73
  # zzz_switch_74:
  #   number: 74
  # zzz_switch_75:
  #   number: 75
  # zzz_switch_76:
  #   number: 76
  # zzz_switch_77:
  #   number: 77
  # zzz_switch_78:
  #   number: 78
  # zzz_switch_79:
  #   number: 79

  # zzz_switch_80:
  #   number: 80  
  # zzz_switch_81:
  #   number: 81
  # zzz_switch_82:
  #   number: 82
  # zzz_switch_83:
  #   number: 83
  # zzz_switch_84:
  #   number: 84
  # zzz_switch_85:
  #   number: 85
  # zzz_switch_86:
  #   number: 86
  # zzz_switch_87:
  #   number: 87
  # zzz_switch_88:
  #   number: 88




#############################

  s_green_button_right:
    number: 56

  # ADMIN --------------------------------------
  s_test_switch:
    number: 7
  s_start:
    number: 47
    tags: start
  
  # TROUGH --------------------------------------
  s_trough_left:
    number: 40
  s_trough_right:
    number: 30
  s_outhole:
    number: 20

  # SUBWAY --------------------------------------
  s_subway_kicker:
    number: 0
  s_subway_one:
    number: 3
  s_subway_lock:
    number: 10

  # RIGHT DROP TARGETS --------------------------
  s_right_drop_target_1:
    number: 1
  s_right_drop_target_2:
    number: 11
  s_right_drop_target_3:
    number: 21
  s_right_drop_target_4:
    number: 31  
  s_right_drop_target_5:
    number: 41

  # TOP DROP TARGETS ----------------------------
  s_top_drop_target_1:
    number: 2
  s_top_drop_target_2:
    number: 12
  s_top_drop_target_3:
    number: 22
  s_top_drop_target_4:
    number: 32
  s_top_drop_target_5:
    number: 42

  # CRATERS -------------------------------------
  s_crater_1:
    number: 34 
    tags: playfield_active
  s_crater_2:
    number: 24    
    tags: playfield_active
  s_crater_3:
    number: 14    
    tags: playfield_active
  s_crater_4:
    number: 4
    tags: playfield_active

  # OUTLANES ------------------------------------
  s_outlane_rollover_right:
    number: 5
    tags: playfield_active
  s_outlane_rollover_left:
    number: 6
    tags: playfield_active

  # POP BUMPERS --------------------------------
  s_top_pop_bumpers_x2:
    number: 35
    tags: playfield_active
  s_bottom_pop_bumpers_x2:
    number: 13
    tags: playfield_active

  # OTHER SWITCHES ------------------------------
  s_10_point_switches_x7:
    number: 15
    tags: playfield_active
  s_return_rollover_left:
    number: 16
    tags: playfield_active
  s_hole_kicker_top:
    number: 23
  s_rollunder:
    number: 25
    tags: playfield_active
  s_kicking_target:
    number: 26
    tags: playfield_active
  s_spot_target:
    number: 36
    tags: playfield_active
  s_side_kicker_left:
    number: 43
  s_spinner:
    number: 44
    tags: playfield_active
  s_tilt_playboard:
    number: 46
    tags: playfield_active



#================================================
# COILS
# xxx xxx xxx xxx xxx xxx xxx
#================================================

coils:
  c_subway_lock:
    number: 1
    default_hold_power: .1
    default_pulse_ms: 300
  c_top_drops:
    number: 2
    default_hold_power: .1
    default_pulse_ms: 300
  # c_CCC:
  #   number: 3
  # c_DDD:
  #   number: 4
  c_subway_kicker:
    number: 5
    default_pulse_ms: 40
  c_right_drops:
    number: 6
    default_hold_power: .1
    default_pulse_ms: 300     
  c_GGG:
    number: 7
  c_Replay_Knock:
    number: 8
    default_pulse_ms: 50
  c_outhole:
    number: 9
    default_pulse_ms: 65 
  c_trough_release:
    number: 115 # uses light bank
    default_hold_power: 0.075
    default_pulse_ms: 30   
  c_side_kicker_left:
    number: 108 # uses light bank
    default_pulse_ms: 15
  c_hole_kicker_top:
    number: 116 # uses light bank
    default_pulse_ms: 55
  c_skill_motor:
    number: 112 # uses light bank
    default_pulse_ms: 5000


  # c_kicker_left:
  #   number: 4
  # c_kicker_right:
  #   number: 4
  # c_ball_return_lane:
  #   number: 4
  # c_kicking_target:
  #   number: 4
  # c_outlane_gate_right:
  #   number: 4
  # c_pop_bumper_1:
  #   number: 4
  # c_pop_bumper_2:
  #   number: 4
  # c_pop_bumper_3:
  #   number: 4
  # c_pop_bumper_4:
  #   number: 4
  # c_right_drop_target_reset:
  #   number: 4
  # c_top_drop_target_reset:
  #   number: 4



#================================================
# LIGHTS
# Controlled illuminations
#================================================

lights:
#   l_tilt_relay:
#     number: 
#   l_high_game_to date:
#     number: 
#   l_same_player_shoots_again:
#     number: 
#   l_game_over_relay:
#     number: 0  
  # l_2000_Bonus:
  #   number: 34
  l_Game_Over_Relay:
    number: 00
  l_BK_Shoot_Again:
    number: 01
  l_Coin_Lockout_Coil:
    number: 02
  l_Bottom_Sht_Again:
    number: 03
  l_2x_Multiplier:
    number: 04
  l_3x_Multiplier:
    number: 05
  l_4x_Multiplier:
    number: 06
  l_5x_Multiplier:
    number: 07
  l_$$_LH_Lava_Pit:
    number: 08
  l_$$_Skill:
    number: 12
  l_$$_RH_Bl_Save:
    number: 14
  l_$$_RH_Bl_Reset:
    number: 15
  l_$$_Top_Hole:
    number: 16
  l_Lava_Level_One:
    number: 17
  l_Lava_Level_Two:
    number: 18
  l_1_Right_Drop_Target:
    number: 19
  l_2_Right_Drop_Target:
    number: 20
  l_3_Right_Drop_Target:
    number: 21
  l_4_Right_Drop_Target:
    number: 22
  l_5_Right_Drop_Target:
    number: 23
  l_Crater_4:
    number: 24
  l_Crater_3:
    number: 25
  l_Crater_2:
    number: 26
  l_Crater_1:
    number: 27
  l_Top_Drop_Target:
    number: 28
  l_Bottom_Drop_Target:
    number: 29
  l_2x_Lava_Flow_Multiplier:
    number: 30
  l_3x_Lava_Flow_Multiplier:
    number: 31
  l_4x_Lava_Flow_Multiplier:
    number: 32
  l_1000_Bonus:
    number: 33
  l_l_2000_Bonus:
    number: 34
  l_3000_Bonus:
    number: 35
  l_4000_Bonus:
    number: 36
  l_5000_Bonus:
    number: 37
  l_6000_Bonus:
    number: 38
  l_7000_Bonus:
    number: 39
  l_8000_Bonus:
    number: 40
  l_9000_Bonus:
    number: 41
  l_10000_Bonus:
    number: 42
  l_Spot_Target:
    number: 43
  l_Special:
    number: 44
  l_Extra_Ball:
    number: 45
  l_Spinner:
    number: 46
  l_Collect_Seismic_Value:
    number: 47


  
  # n/a lights:
  #   number: 09
  #   number: 10
  #   number: 11
  #   number: 13
  #   number: 48
  #   number: 49
  #   number: 50
  #   number: 51



#================================================
# BALL DEVICES
# Controlled devices that HOLD a ball
#================================================
ball_devices:
  bd_drain:
    ball_switches: s_outhole
    eject_coil: c_outhole
    eject_targets: bd_trough
    tags: drain
    eject_timeouts: 2s
    debug: yes
  bd_trough:
    entrance_switch: s_trough_left
    entrance_switch_full_timeout: 1.5s
    entrance_switch_ignore_window_ms: 1s
    entrance_count_delay: 1.25s
    ball_capacity: 3
    eject_coil: c_trough_release
    eject_coil_enable_time: 700ms
    eject_timeouts: 1.5s
    tags: trough, home
    debug: True
  bd_side_kicker_left:
    ball_switches: s_side_kicker_left
    eject_coil: c_side_kicker_left
    tags: playfield_active
    entrance_count_delay: 1500
  bd_hole_kicker_top:
    ball_switches: s_hole_kicker_top
    eject_coil: c_hole_kicker_top
    tags: playfield_active
    entrance_count_delay: 1500    
  bd_subway_kicker_:
    ball_switches: s_subway_kicker
    eject_coil: c_subway_kicker
    tags: playfield_active
    entrance_count_delay: 1500    
  bd_subway_lock:
    ball_switches: s_subway_lock
    eject_coil: c_subway_lock
    # tags: playfield_active
    # entrance_count_delay: 500
    eject_timeouts: 1s  
  bd_skill_motor:
    ball_switches: s_green_button_right
    eject_coil: c_skill_motor
    tags: playfield_active

    
playfields:
  playfield:
    default_source_device: bd_trough
    tags: default
    




########################################


drop_targets:
    top_drop_target_1:
         switch: s_top_drop_target_1
    top_drop_target_2:
         switch: s_top_drop_target_2
    top_drop_target_3:
         switch: s_top_drop_target_3
    top_drop_target_4:
         switch: s_top_drop_target_4
    top_drop_target_5:
         switch: s_top_drop_target_5
    right_drop_target_1:
         switch: s_right_drop_target_1
    right_drop_target_2:
         switch: s_right_drop_target_2
    right_drop_target_3:
         switch: s_right_drop_target_3
    right_drop_target_4:
         switch: s_right_drop_target_4
    right_drop_target_5:
         switch: s_right_drop_target_5

drop_target_banks:

  top_bank:
    drop_targets: top_drop_target_1, top_drop_target_2, top_drop_target_3, top_drop_target_4, top_drop_target_5
    reset_coil: c_top_drops
    reset_coil_max_wait_ms: 150
    reset_events: 
      machine_reset_phase_3: 0
      ball_will_end: 100ms
      resetTopDrops: 500ms
      # ball_starting: 100ms
      # mode_punchOutAward_started: 0
      # mode_punchOutAward_stopped: 0
      # mode_precisionAward_started: 0
      # mode_multiball_ttSTD_started: 0
      # mode_multiball_ttSTD_stopped: 0

  right_bank:
    drop_targets: right_drop_target_1, right_drop_target_2, right_drop_target_3, right_drop_target_4, right_drop_target_5
    reset_coil: c_right_drops
    reset_coil_max_wait_ms: 150
    reset_events: 
      machine_reset_phase_3: 100ms
      ball_will_end: 100ms
      resetRightDrops: 500ms
      # ball_starting: 100ms
      # mode_punchOutAward_started: 100ms
      # mode_punchOutAward_stopped: 100ms
      # mode_precisionAward_started: 100ms
      # mode_multiball_ttSTD_started: 100ms
      # mode_multiball_ttSTD_stopped: 100ms
      # 
                    


    
digital_outputs:
  game_over_relay:
    number: 0
    type: light
    enable_events: ball_started
    disable_events: ball_will_end

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60
  attract_started:
    widgets:
      - text: Juke in the Back
        type: text

slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started
  # ball_started:
  #   widgets:
  #     type: text
  #     text: PLAYER (number) BALL (ball)














