#config_version=6

lights:
#   l_tilt_relay:
#     number: 
#   l_high_game_to date:
#     number: 
#   l_same_player_shoots_again:
#     number: 

  l_game_over_relay_00:
    number: 00
  l_xxx_01:
    number: 01
  l_xxx_02:
    number: 02
  l_xxx_03:
    number: 03
  l_xxx_04:
    number: 04
  l_xxx_05:
    number: 05
  l_xxx_06:
    number: 06
  l_xxx_07:
    number: 07
  l_xxx_08:
    number: 08
  l_xxx_12:
    number: 12
  l_xxx_14:
    number: 14
  l_xxx_15:
    number: 15
  l_xxx_16:
    number: 16
  l_xxx_17:
    number: 17
  l_xxx_18:
    number: 18
  l_xxx_19:
    number: 19
  l_xxx_20:
    number: 20
  l_xxx_21:
    number: 21
  l_xxx_22:
    number: 22
  l_xxx_23:
    number: 23
  l_xxx_24:
    number: 24
  l_xxx_25:
    number: 25
  l_xxx_26:
    number: 26
  l_xxx_27:
    number: 27
  l_xxx_28:
    number: 28
  l_xxx_29:
    number: 29
  l_xxx_30:
    number: 30
  l_xxx_31:
    number: 31
  l_xxx_32:
    number: 32
  l_xxx_33:
    number: 33
  l_xxx_34:
    number: 34
  l_xxx_35:
    number: 35
  l_xxx_36:
    number: 36
  l_xxx_37:
    number: 37
  l_xxx_38:
    number: 38
  l_xxx_39:
    number: 39
  l_xxx_40:
    number: 40
  l_xxx_41:
    number: 41
  l_xxx_42:
    number: 42
  l_xxx_43:
    number: 43
  l_xxx_44:
    number: 44
  l_xxx_45:
    number: 45
  l_xxx_46:
    number: 46
  l_xxx_47:
    number: 47


  
  # n/a lights:
  #   number: 09
  #   number: 10
  #   number: 11
  #   number: 13
  #   number: 48
  #   number: 49
  #   number: 50
  #   number: 51
