#config_version=6

switches:

  # TUTORIAL --------------------------------------
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  s_plunger_lane:
    number:

  # CABINET --------------------------------------
  s_green_button_right_56:
    number: 56

  # ADMIN --------------------------------------
  s_test_switch_7:
    number: 7
  s_start_47:
    number: 47
    tags: start
  
  # TROUGH --------------------------------------
  s_trough_1_40:
    number: 40
  s_trough_2_30:
    number: 30
  s_trough_3_20:
    number: 20

  # SUBWAY --------------------------------------
  s_subway_kicker_0:
    number: 0
  s_subway_one_3:
    number: 3
  s_subway_lock_10:
    number: 10

  # RIGHT DROP TARGETS --------------------------
  s_right_drop_1_1:
    number: 1
  s_right_drop_2_11:
    number: 11
  s_right_drop_3_21:
    number: 21
  s_right_drop_4_31:
    number: 31  
  s_right_drop_5_41:
    number: 41

  # TOP DROP TARGETS ----------------------------
  s_top_drop_1_2:
    number: 2
  s_top_drop_2_12:
    number: 12
  s_top_drop_3_22:
    number: 22
  s_top_drop_4_32:
    number: 32
  s_top_drop_5_42:
    number: 42

  # RAMP -------------------------------------
  s_ramp_1_34:
    number: 34 
  s_ramp_2_24:
    number: 24    
  s_ramp_3_14:
    number: 14    
  s_ramp_4_4:
    number: 4

  # OUTLANES ------------------------------------
  s_outlane_right_5:
    number: 5
  s_outlane_left_6:
    number: 6

  # POP BUMPERS --------------------------------
  s_top_bumpers_35:
    number: 35
  s_bottom_bumpers_13:
    number: 13

  # OTHER SWITCHES ------------------------------
  s_10_points_15:
    number: 15
  s_return_left_16:
    number: 16
  s_hole_kicker_top_23:
    number: 23
  s_rollunder_25:
    number: 25
  s_kicking_target_26:
    number: 26
  s_spot_target_36:
    number: 36
  s_side_kicker_left_43:
    number: 43
  s_spinner_44:
    number: 44
  s_tilt_46:
    number: 46

