#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml
  - config_lights.yaml
  - config_drop_targets.yaml

modes:
  - attract
  - base
  - bumpers
  - hurryup
  - right_drops

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default

virtual_platform_start_active_switches:
  - s_trough_1_40
  - s_trough_2_30
  - s_trough_3_20