#config_version=6

ball_devices:
  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true
  bd_trough:
    ball_switches: s_trough_1_40, s_trough_2_30, s_trough_3_20
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain